apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-truststore-ibm-truststore-mgr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-cp-truststore
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/gitops-cp-truststore/ibm-truststore-mgr
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-truststore-ocp4
    targetRevision: main
    helm:
      releaseName: ibm-truststore-mgr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
