apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-truststore-ibm-entitlement-key
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-cp-truststore
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: >-
      payload/1-infrastructure/namespace/gitops-cp-truststore/ibm-entitlement-key
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-truststore-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
